name: greengridhill
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Firebase Integration
  firebase_core: ^4.6.0
  firebase_database: ^12.2.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  google_sign_in: ^7.2.0
  
  # MQTT Communication
  mqtt_client: ^10.4.0
  
  # Data Visualization
  syncfusion_flutter_charts: ^33.1.47
  syncfusion_flutter_gauges: ^33.1.47
  
  # Local Storage
  shared_preferences: ^2.3.3
  
  # Notifications
  flutter_local_notifications: ^21.0.0
  
  # HTTP Communication
  http: ^1.2.2
  
  # Utilities
  google_fonts: ^8.0.2
  video_player: ^2.11.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
